### ISSUE TITLE
请问怎么刷写固件

### ISSUE THREAD

**Issue by Tao173** [SmartArduino/DoHome#1]
u1.bin	
u2.bin
这两个固件刷哪个？？？刷入之后可以直接使用了么？？？

**Comment by baoshuai9527** [comment]
下载其中一个即可

固件 | 下载地址
-- | --
rboot.bin | 0x0000
blank_config.bin | 0x1000
u1.bin | 0x2000
u2.bin | 0x81000

**Comment by Tao173** [comment]
我在淘宝购买的esp8266,可以直接刷这个固件么？？？？=能不能正常使用？？？谢谢之前的回复

**Comment by baoshuai9527** [comment]
> 我在淘宝购买的esp8266,可以直接刷这个固件么？？？？=能不能正常使用？？？谢谢之前的回复

可以，下载就能用

**Comment by Tao173** [comment]
好的，谢谢回复。
