### ISSUE TITLE
Problem to load Homeassistant component (dohomelight.light)

### ISSUE THREAD

**Issue by vjccruz** [SmartArduino/DoHome#8]
Hello,

When try load the home assistant component, I get this error:
`Log Details (ERROR)`
`Logger: homeassistant.setup`
`Source: setup.py:280`
`First occurred: 10:28:14 AM (1 occurrences)`
`Last logged: 10:28:14 AM`
`Unable to prepare setup for platform dohomelight.light: Platform not found (No module named 'custom_components.dohomelight.light').`

I checked the folder dohomelight and not exist a light.py file, I thing is can be the problem.

Best regards,
Vasco Cruz

**Comment by HoGC** [comment]
Added！
Thank you for your feedback
